import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Container, Text, useColorMode, Button, Box, Stack, Heading } from '@chakra-ui/react'
import { MoonIcon } from '@chakra-ui/icons'
import Navbar from '../packages/stateless/components/Navbar'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const { colorMode, toggleColorMode } = useColorMode()

  return (
    <>
      <Head>
        <title>Quasar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container maxW={'3xl'}>
            <Stack  as={Box}
                textAlign={'center'}
                spacing={{ base: 8, md: 14 }}
                py={{ base: 10, md: 20 }}>
                  <Heading  fontWeight={600}
                            fontSize={{ base: '2xl', sm: '4xl', md: '5xl' }}
                            lineHeight={'100%'}
                            color='white'
                            mt={20}>
                              Transparent Judging and Voting
                  </Heading>
                            <Text color='white'>
                            Quasar Module is a smart contract application and framework for custom IRL events.
                            </Text>
            </Stack>
      </Container>
    </>
  )
}
